2021-05-20 18:45:15.214 +06:00 [INF] Application Starting up
2021-05-20 18:51:21.395 +06:00 [WRN] Invalid password for user c9c54026-b037-49b8-6486-08d9117b0ba0.
2021-05-20 18:51:21.408 +06:00 [WRN] User c9c54026-b037-49b8-6486-08d9117b0ba0 failed to provide the correct password.
2021-05-20 18:51:29.067 +06:00 [INF] User logged in.
2021-05-20 19:09:09.069 +06:00 [INF] User logged in.
2021-05-20 19:19:51.755 +06:00 [INF] User created a new account with password.
2021-05-20 19:22:26.242 +06:00 [INF] User logged in.
2021-05-20 19:25:52.623 +06:00 [INF] User logged in.
2021-05-20 19:47:13.214 +06:00 [INF] User logged in.
2021-05-20 19:53:13.435 +06:00 [INF] User logged in.
2021-05-20 19:54:23.480 +06:00 [INF] User logged in.
2021-05-20 19:55:01.748 +06:00 [INF] User logged in.
2021-05-20 20:26:12.708 +06:00 [INF] User logged in.
2021-05-20 21:05:32.087 +06:00 [INF] Application Starting up
2021-05-20 21:15:09.834 +06:00 [INF] User logged in.
2021-05-20 21:39:04.245 +06:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Demo.DataAccessLayer.Repository`3.GetAll() in E:\6_DIU\DIU PROJECT\PROJECT\Final-Project\E-Election Voting\Demo.DataAccessLayer\Repository.cs:line 85
   at Demo.Foundation.Services.GetService.GetMakeElectionList() in E:\6_DIU\DIU PROJECT\PROJECT\Final-Project\E-Election Voting\Demo.Foundation\Services\GetService.cs:line 53
   at Demo.Web.Models.ViewModel.LoadElectionsDataTable() in E:\6_DIU\DIU PROJECT\PROJECT\Final-Project\E-Election Voting\Demo.Web\Models\ViewModel.cs:line 151
   at Demo.Web.Areas.Admin.Controllers.RegistrationController.GetAllElectionDataTable() in E:\6_DIU\DIU PROJECT\PROJECT\Final-Project\E-Election Voting\Demo.Web\Areas\Admin\Controllers\RegistrationController.cs:line 59
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
